### ISSUE TITLE
Not showing any notification

### ISSUE THREAD

**Issue by RickyWLam** [patoliavishal/flutter-FCM#4]
Please help. Android Emulator is running but not showing any notification.  
I used Firebase - message - new campaign to send Notifications. 

W/er_notificatio( 1239): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/er_notificatio( 1239): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
I/flutter ( 1239): A new event was published!
D/CompatibilityChangeReporter( 1239): Compat change id reported: 160794467; UID 10150; state: ENABLED

**Comment by patoliavishal** [comment]
Can you try with real device?
